"""Skill Forge — generates reusable scraping skills from website exploration.

Pipeline:
1. Explore site — discover API endpoints via network capture, DOM fallback
2. Generate — produce parameterized Python script + SKILL.md
3. Self-test — validate the generated skill works

Output format:
    output/{skill-name}/
    ├── SKILL.md          — agent skill definition
    ├── skill.py          — executable Python script
    └── requirements.txt  — dependencies
"""

from pathlib import Path
from typing import Optional


def generate_skill_skeleton(
    skill_name: str,
    description: str,
    target_url: str,
    parameters: list[dict],
    extraction_js: str,
    output_dir: Optional[str] = None,
) -> dict:
    """Generate a complete skill package from exploration results."""

    if output_dir is None:
        output_dir = f"output/{skill_name}"

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    param_names = [p["name"] for p in parameters]
    param_help = {p["name"]: p.get("description", "") for p in parameters}

    skill_py = _generate_skill_script(
        skill_name=skill_name,
        description=description,
        target_url=target_url,
        param_names=param_names,
        param_help=param_help,
        extraction_js=extraction_js,
    )

    skill_md = _generate_skill_md(
        skill_name=skill_name,
        description=description,
        target_url=target_url,
        parameters=parameters,
    )

    (out_path / "skill.py").write_text(skill_py, encoding="utf-8")
    (out_path / "SKILL.md").write_text(skill_md, encoding="utf-8")
    (out_path / "requirements.txt").write_text("freeact>=0.1.0\nplaywright>=1.40\n", encoding="utf-8")

    return {
        "ok": True,
        "output_dir": str(out_path),
        "files": ["skill.py", "SKILL.md", "requirements.txt"],
        "message": f"Skill '{skill_name}' generated in {out_path}",
    }


def _generate_skill_script(
    skill_name: str,
    description: str,
    target_url: str,
    param_names: list[str],
    param_help: dict[str, str],
    extraction_js: str,
) -> str:
    params_block = "\n".join(
        f'    parser.add_argument("--{p}", type=str, default="", help="{param_help.get(p, "")}")'
        for p in param_names
    )

    js_escaped = extraction_js.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")

    return f'''"""Skill: {skill_name} — {description}

Generated by FreeAct Skill Forge.
Target: {target_url}
"""

import argparse
import json
import sys
from pathlib import Path

try:
    from freeact.daemon import send_daemon_command, is_daemon_running
except ImportError:
    print("Error: freeact not installed. Run: pip install freeact")
    sys.exit(1)


EXTRACTION_JS = """{js_escaped}"""


def extract_data({", ".join(f"{p}: str = ''" for p in param_names)}) -> list[dict]:
    """Extract data using the explored API/DOM path."""

    if not is_daemon_running():
        print("Error: freeact daemon not running. Start with: freeact daemon")
        return []

    # Build URL with parameters
    url = "{target_url}"
    search_term = " ".join(filter(None, [{", ".join(param_names)}]))
    if search_term:
        url = url + "?search=" + search_term.replace(" ", "+")

    # Open browser and navigate
    skill_name = "skill-{skill_name}"
    result = send_daemon_command("/cmd/browser", {{
        "action": "open",
        "browser_id": skill_name,
        "url": url,
        "session": skill_name,
    }})

    if not result.get("ok"):
        print(f"Error opening browser: {{result.get('error')}}")
        return []

    import time
    time.sleep(3)

    # Execute extraction JavaScript
    eval_result = send_daemon_command("/cmd/eval", {{
        "session": skill_name,
        "js": EXTRACTION_JS,
    }})

    if not eval_result.get("ok"):
        print(f"Error extracting data: {{eval_result.get('error')}}")
        return []

    try:
        data = json.loads(eval_result["result"])
        return data if isinstance(data, list) else [data]
    except json.JSONDecodeError:
        print(f"Could not parse result as JSON")
        return []


def main():
    parser = argparse.ArgumentParser(description="{description}")
{params_block}
    parser.add_argument("--output", "-o", type=str, default="output.json", help="Output file")
    args = parser.parse_args()

    params = {{}}
    for param in {param_names}:
        params[param] = getattr(args, param, "")

    print(f"Extracting data from {target_url}...")
    results = extract_data(**params)

    if results:
        output_path = Path(args.output)
        output_path.write_text(json.dumps(results, indent=2, ensure_ascii=False))
        print(f"Extracted {{len(results)}} records -> {{output_path}}")
    else:
        print("No data extracted")
        sys.exit(1)


if __name__ == "__main__":
    main()
'''


def _generate_skill_md(
    skill_name: str,
    description: str,
    target_url: str,
    parameters: list[dict],
) -> str:
    params_doc = "\n".join(
        f"| `--{p['name']}` | {p.get('description', '')} | {p.get('default', '')} |"
        for p in parameters
    )

    if params_doc:
        params_table = f"""### Parameters

| Parameter | Description | Default |
|-----------|-------------|---------|
{params_doc}
"""
    else:
        params_table = ""

    return f"""---
name: {skill_name}
description: "{description} — skill generated by FreeAct Skill Forge. Use when the user asks to extract data from {target_url}."
allowed-tools: Bash(python:*)
metadata:
  generator: freeact-skill-forge
  target_url: {target_url}
---

# {skill_name}

{description}

**Target:** {target_url}

## Quick Start

```bash
cd {skill_name}
python skill.py --search "keyword" -o results.json
```

{params_table}

## How it works

This skill was generated by FreeAct Skill Forge. It uses the freeact daemon
to control a real browser, extract data, and return structured results.

## Requirements

```bash
pip install freeact
playwright install chromium
```

## Usage

1. Start the freeact daemon:
```bash
freeact daemon
```

2. Run the skill:
```bash
python skill.py --keyword "search term" -o results.json
```
"""


def explore_and_generate(
    skill_name: str,
    target_url: str,
    description: str,
    parameters: list[dict],
    output_dir: Optional[str] = None,
) -> dict:
    """Full pipeline: generate a skill package ready for deployment."""
    return generate_skill_skeleton(
        skill_name=skill_name,
        description=description,
        target_url=target_url,
        parameters=parameters,
        extraction_js="JSON.stringify(document.title)",
        output_dir=output_dir,
    )
